name: Veracode Build
on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      ref:
        required: true
        type: string
      token:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: janthony1986/scm-packaging:1.1.1
    env:
      VERACODE_API_KEY_ID: '${{ secrets.VERACODE_API_ID }}'
      VERACODE_API_KEY_SECRET: '${{ secrets.VERACODE_API_KEY }}'
    steps:
    - uses: actions/checkout@v4
      with:
        path: 'veracode-helper'

    - name: Package the application
      id: application_package
      env:
        VERACODE_API_KEY_ID: '${{ secrets.VERACODE_API_ID }}'
        VERACODE_API_KEY_SECRET: '${{ secrets.VERACODE_API_KEY }}'
      run: |
        git clone https://github.com/rubyrailstesting/chatwoo.git
        export PATH="/home/luser/.rvm/bin:$PATH"
        ls -lart
        rvm pkg install openssl
        rvm install ruby-3.2.2 -C --with-openssl-dir=/home/luser/.rvm/usr/
        /bin/bash --login
        rvm use 3.2.2 --default
        cd veracode-helper/helper/cli
        cliFile=$(ls -1 . | head -n 1)
        cliFileName=$(echo "$cliFile" | cut -c 1-$((${#cliFile}-7)))
        tar -zxvf $cliFile
        cd $cliFileName
        export PATH="veracode-helper/helper/cli/$cliFileName:$PATH"
        cd /__w/veracode/veracode
        cd chatwoot
        sudo gem install rubygems-update
        sudo update_rubygems
        sudo gem update --system
        sudo gem install bundler -v "2.4.6"
        bundle install
        veracode package --source ./chatwoot --output /__w/veracode/veracode/veracode-artifacts --trust
        cd ../
        zip veracode-artifact.zip veracode-artifacts/* -x .zip .tar .tar.gz .gz

    - name: Package error
      if: failure() && steps.application_package.outcome == 'failure'
      run: |
        echo "::error::Veracode static scan faced a problem. Please contact your Veracode administrator for more information."

    - uses: actions/upload-artifact@v4
      with:
        name: veracode-artifact
        path: /__w/veracode/veracode/veracode-artifacts/*
        if-no-files-found: error
